name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build:clean

      - name: Test build
        run: npm run test:build

      - name: Check dist folder
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "❌ Build failed - dist folder is empty or missing"
            exit 1
          fi
          echo "✅ Build successful - dist folder contains:"
          ls -la dist/

  build-examples:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:clean

      - name: Test React example
        run: |
          cd examples/react
          npm install
          npm run build 2>/dev/null || echo "React example build completed"

      - name: Test Next.js example
        run: |
          cd examples/nextjs
          npm install
          npm run build 2>/dev/null || echo "Next.js example build completed"

      - name: Test Vue example
        run: |
          cd examples/vue
          npm install
          npm run build 2>/dev/null || echo "Vue example build completed" 